[package]
name = "mut_paint"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
const_format = "0.2.35"
gtk = { version = "0.10.1", package = "gtk4", features = ["v4_14"] }
image = "0.25.8"
rand = "0.9.2"

[build-dependencies]
glib-build-tools = "0.21.0"